[2023-07-28T15:30:39.766+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Extract manual__2023-07-28T15:30:35.770370+00:00 [queued]>
[2023-07-28T15:30:39.772+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Extract manual__2023-07-28T15:30:35.770370+00:00 [queued]>
[2023-07-28T15:30:39.772+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-28T15:30:39.782+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): Extract> on 2023-07-28 15:30:35.770370+00:00
[2023-07-28T15:30:39.786+0000] {standard_task_runner.py:57} INFO - Started process 296 to run task
[2023-07-28T15:30:39.788+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'toronto_real_estate_etl', 'Extract', 'manual__2023-07-28T15:30:35.770370+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp0qawcdjs']
[2023-07-28T15:30:39.790+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask Extract
[2023-07-28T15:30:39.824+0000] {task_command.py:410} INFO - Running <TaskInstance: toronto_real_estate_etl.Extract manual__2023-07-28T15:30:35.770370+00:00 [running]> on host e5187b3c4256
[2023-07-28T15:30:39.878+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='toronto_real_estate_etl' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-07-28T15:30:35.770370+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-28T15:30:35.770370+00:00'
[2023-07-28T15:30:39.879+0000] {main.py:31} INFO - https://www.kijiji.ca/b-apartments-condos/page-1/c37l1700273
[2023-07-28T15:31:15.073+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-07-28T15:31:15.075+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 296. PIDs of all processes in the group: [296]
[2023-07-28T15:31:15.075+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 296
[2023-07-28T15:31:15.075+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-28T15:31:15.083+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/main.py", line 69, in extract
    e.getListings(2)
  File "/opt/airflow/dags/src/main.py", line 49, in getListings
    time.sleep(3)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-28T15:31:15.086+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=toronto_real_estate_etl, task_id=Extract, execution_date=20230728T153035, start_date=20230728T153039, end_date=20230728T153115
[2023-07-28T15:31:15.096+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 34 for task Extract (Task received SIGTERM signal; 296)
[2023-07-28T15:31:15.128+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=296, status='terminated', exitcode=1, started='15:30:39') (296) terminated with exit code 1
