[2023-07-28T13:30:06.651+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Extract manual__2023-07-28T13:20:10.849176+00:00 [queued]>
[2023-07-28T13:30:06.660+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: toronto_real_estate_etl.Extract manual__2023-07-28T13:20:10.849176+00:00 [queued]>
[2023-07-28T13:30:06.660+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-28T13:30:06.671+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): Extract> on 2023-07-28 13:20:10.849176+00:00
[2023-07-28T13:30:06.675+0000] {standard_task_runner.py:57} INFO - Started process 5038 to run task
[2023-07-28T13:30:06.678+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'toronto_real_estate_etl', 'Extract', 'manual__2023-07-28T13:20:10.849176+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpigygwjkh']
[2023-07-28T13:30:06.680+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask Extract
[2023-07-28T13:30:06.715+0000] {task_command.py:410} INFO - Running <TaskInstance: toronto_real_estate_etl.Extract manual__2023-07-28T13:20:10.849176+00:00 [running]> on host 7d0ee807347f
[2023-07-28T13:30:06.777+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='toronto_real_estate_etl' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-07-28T13:20:10.849176+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-28T13:20:10.849176+00:00'
[2023-07-28T13:30:06.778+0000] {main.py:30} INFO - https://www.kijiji.ca/b-apartments-condos/page-1/c37l1700273
[2023-07-28T13:32:27.600+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-07-28T13:32:27.601+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 5038. PIDs of all processes in the group: [5038]
[2023-07-28T13:32:27.601+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 5038
[2023-07-28T13:32:27.602+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-28T13:32:27.610+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/main.py", line 68, in extract
    e.getListings(2)
  File "/opt/airflow/dags/src/main.py", line 48, in getListings
    time.sleep(3)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-28T13:32:27.614+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=toronto_real_estate_etl, task_id=Extract, execution_date=20230728T132010, start_date=20230728T133006, end_date=20230728T133227
[2023-07-28T13:32:27.625+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 16 for task Extract (Task received SIGTERM signal; 5038)
[2023-07-28T13:32:27.654+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5038, status='terminated', exitcode=1, started='13:30:06') (5038) terminated with exit code 1
