[2023-07-23T09:40:34.339+0000] {processor.py:157} INFO - Started process (PID=312) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:40:34.341+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:40:34.342+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:40:34.341+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:40:34.355+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:40:34.349+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from ingestion_functions import stackoverflow_api_to_csv,insert_all_csv_files_into_postgres_table
ModuleNotFoundError: No module named 'ingestion_functions'
[2023-07-23T09:40:34.356+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:40:34.383+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.052 seconds
[2023-07-23T09:41:04.484+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:41:04.485+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:41:04.486+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:41:04.486+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:41:04.489+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:41:04.488+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from ingestion_functions import stackoverflow_api_to_csv,insert_all_csv_files_into_postgres_table
ModuleNotFoundError: No module named 'ingestion_functions'
[2023-07-23T09:41:04.489+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:41:04.506+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.024 seconds
[2023-07-23T09:41:34.618+0000] {processor.py:157} INFO - Started process (PID=328) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:41:34.628+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:41:34.629+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:41:34.629+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:41:34.631+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:41:34.631+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from ingestion_functions import stackoverflow_api_to_csv,insert_all_csv_files_into_postgres_table
ModuleNotFoundError: No module named 'ingestion_functions'
[2023-07-23T09:41:34.632+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:41:34.648+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.032 seconds
[2023-07-23T09:42:04.755+0000] {processor.py:157} INFO - Started process (PID=336) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:42:04.756+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:42:04.757+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:42:04.756+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:42:04.759+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:42:04.759+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from ingestion_functions import stackoverflow_api_to_csv,insert_all_csv_files_into_postgres_table
ModuleNotFoundError: No module named 'ingestion_functions'
[2023-07-23T09:42:04.760+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:42:04.776+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.023 seconds
[2023-07-23T09:42:34.897+0000] {processor.py:157} INFO - Started process (PID=343) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:42:34.898+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:42:34.898+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:42:34.898+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:42:34.901+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:42:34.900+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from ingestion_functions import stackoverflow_api_to_csv,insert_all_csv_files_into_postgres_table
ModuleNotFoundError: No module named 'ingestion_functions'
[2023-07-23T09:42:34.901+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:42:34.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.025 seconds
[2023-07-23T09:43:05.031+0000] {processor.py:157} INFO - Started process (PID=351) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:43:05.032+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:43:05.033+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:43:05.032+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:43:05.037+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:43:05.035+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from ingestion_functions import stackoverflow_api_to_csv,insert_all_csv_files_into_postgres_table
ModuleNotFoundError: No module named 'ingestion_functions'
[2023-07-23T09:43:05.037+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:43:05.054+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.027 seconds
[2023-07-23T09:43:35.164+0000] {processor.py:157} INFO - Started process (PID=359) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:43:35.173+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:43:35.173+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:43:35.173+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:43:35.176+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:43:35.175+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from ingestion_functions import stackoverflow_api_to_csv,insert_all_csv_files_into_postgres_table
ModuleNotFoundError: No module named 'ingestion_functions'
[2023-07-23T09:43:35.176+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:43:35.192+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.030 seconds
[2023-07-23T09:44:05.294+0000] {processor.py:157} INFO - Started process (PID=367) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:44:05.295+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:44:05.295+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:44:05.295+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:44:05.299+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:44:05.298+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from ingestion_functions import stackoverflow_api_to_csv,insert_all_csv_files_into_postgres_table
ModuleNotFoundError: No module named 'ingestion_functions'
[2023-07-23T09:44:05.299+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:44:05.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.023 seconds
[2023-07-23T09:44:35.418+0000] {processor.py:157} INFO - Started process (PID=375) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:44:35.420+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:44:35.421+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:44:35.421+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:44:35.424+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:44:35.423+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from ingestion_functions import stackoverflow_api_to_csv,insert_all_csv_files_into_postgres_table
ModuleNotFoundError: No module named 'ingestion_functions'
[2023-07-23T09:44:35.424+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:44:35.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.024 seconds
[2023-07-23T09:44:39.445+0000] {processor.py:157} INFO - Started process (PID=376) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:44:39.445+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:44:39.446+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:44:39.446+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:44:39.449+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:44:39.448+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from Load import Load
ModuleNotFoundError: No module named 'Load'
[2023-07-23T09:44:39.449+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:44:39.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.021 seconds
[2023-07-23T09:45:05.564+0000] {processor.py:157} INFO - Started process (PID=384) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:45:05.565+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:45:05.566+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:45:05.565+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:45:05.569+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:45:05.568+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from Load import Load
ModuleNotFoundError: No module named 'Load'
[2023-07-23T09:45:05.569+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:45:05.585+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.023 seconds
[2023-07-23T09:45:35.717+0000] {processor.py:157} INFO - Started process (PID=392) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:45:35.726+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:45:35.727+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:45:35.727+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:45:35.730+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:45:35.729+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from Load import Load
ModuleNotFoundError: No module named 'Load'
[2023-07-23T09:45:35.730+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:45:35.750+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.036 seconds
[2023-07-23T09:46:05.843+0000] {processor.py:157} INFO - Started process (PID=400) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:46:05.844+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:46:05.844+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:46:05.844+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:46:05.847+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:46:05.846+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from Load import Load
ModuleNotFoundError: No module named 'Load'
[2023-07-23T09:46:05.847+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:46:05.862+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.021 seconds
[2023-07-23T09:46:35.966+0000] {processor.py:157} INFO - Started process (PID=408) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:46:35.970+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:46:35.970+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:46:35.970+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:46:35.973+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:46:35.973+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from Load import Load
ModuleNotFoundError: No module named 'Load'
[2023-07-23T09:46:35.974+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:46:35.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.026 seconds
[2023-07-23T09:47:03.085+0000] {processor.py:157} INFO - Started process (PID=416) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:47:03.085+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:47:03.086+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:47:03.085+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:47:03.089+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:47:03.088+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:47:03.089+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:47:03.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.022 seconds
[2023-07-23T09:47:33.213+0000] {processor.py:157} INFO - Started process (PID=424) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:47:33.222+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:47:33.223+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:47:33.223+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:47:33.227+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:47:33.225+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:47:33.227+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:47:33.246+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.036 seconds
[2023-07-23T09:48:03.332+0000] {processor.py:157} INFO - Started process (PID=432) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:48:03.333+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:48:03.333+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:48:03.333+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:48:03.337+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:48:03.336+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:48:03.337+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:48:03.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.029 seconds
[2023-07-23T09:48:33.460+0000] {processor.py:157} INFO - Started process (PID=440) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:48:33.462+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:48:33.463+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:48:33.463+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:48:33.466+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:48:33.465+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:48:33.467+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:48:33.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.035 seconds
[2023-07-23T09:49:03.590+0000] {processor.py:157} INFO - Started process (PID=448) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:49:03.591+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:49:03.591+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:49:03.591+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:49:03.594+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:49:03.594+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:49:03.595+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:49:03.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.023 seconds
[2023-07-23T09:49:18.660+0000] {processor.py:157} INFO - Started process (PID=449) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:49:18.669+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:49:18.670+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:49:18.670+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:49:18.673+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:49:18.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:49:18.673+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:49:18.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.028 seconds
[2023-07-23T09:49:35.736+0000] {processor.py:157} INFO - Started process (PID=457) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:49:35.737+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:49:35.737+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:49:35.737+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:49:35.740+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:49:35.739+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:49:35.740+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:49:35.756+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.022 seconds
[2023-07-23T09:50:02.851+0000] {processor.py:157} INFO - Started process (PID=465) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:50:02.852+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:50:02.852+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:50:02.852+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:50:02.855+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:50:02.854+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7
    from main
             ^
SyntaxError: invalid syntax
[2023-07-23T09:50:02.855+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:50:02.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.022 seconds
[2023-07-23T09:50:26.969+0000] {processor.py:157} INFO - Started process (PID=466) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:50:26.970+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:50:26.970+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:50:26.970+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:50:26.974+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:50:26.973+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import Extract
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:50:26.974+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:50:26.990+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.024 seconds
[2023-07-23T09:50:43.070+0000] {processor.py:157} INFO - Started process (PID=474) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:50:43.080+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:50:43.080+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:50:43.080+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:50:43.083+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:50:43.082+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import Extract
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:50:43.083+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:50:43.099+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.031 seconds
[2023-07-23T09:51:13.200+0000] {processor.py:157} INFO - Started process (PID=482) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:51:13.201+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:51:13.202+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:51:13.201+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:51:13.206+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:51:13.204+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import Extract
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:51:13.206+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:51:13.225+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.027 seconds
[2023-07-23T09:51:43.328+0000] {processor.py:157} INFO - Started process (PID=490) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:51:43.329+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:51:43.330+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:51:43.330+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:51:43.333+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:51:43.332+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import Extract
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:51:43.333+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:51:43.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.023 seconds
[2023-07-23T09:52:13.467+0000] {processor.py:157} INFO - Started process (PID=498) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:52:13.468+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:52:13.470+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:52:13.469+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:52:13.473+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:52:13.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from main import Extract
ModuleNotFoundError: No module named 'main'
[2023-07-23T09:52:13.473+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:52:13.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.028 seconds
[2023-07-23T09:52:31.550+0000] {processor.py:157} INFO - Started process (PID=499) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:52:31.558+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:52:31.559+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:52:31.559+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:52:31.707+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:52:31.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import Extract
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:52:31.708+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:52:31.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.178 seconds
[2023-07-23T09:53:01.833+0000] {processor.py:157} INFO - Started process (PID=507) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:53:01.834+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:53:01.835+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:53:01.835+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:53:01.898+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:53:01.897+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import Extract
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:53:01.898+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:53:01.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.085 seconds
[2023-07-23T09:53:31.960+0000] {processor.py:157} INFO - Started process (PID=515) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:53:31.969+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:53:31.970+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:53:31.969+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:53:32.035+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:53:32.034+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import Extract
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:53:32.036+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:53:32.052+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.094 seconds
[2023-07-23T09:53:57.116+0000] {processor.py:157} INFO - Started process (PID=523) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:53:57.117+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:53:57.117+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:53:57.117+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:53:57.188+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:53:57.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:53:57.188+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:53:57.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.093 seconds
[2023-07-23T09:54:02.160+0000] {processor.py:157} INFO - Started process (PID=524) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:54:02.161+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:54:02.161+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:54:02.161+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:54:02.238+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:54:02.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:54:02.238+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:54:02.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.099 seconds
[2023-07-23T09:54:26.347+0000] {processor.py:157} INFO - Started process (PID=532) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:54:26.349+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:54:26.351+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:54:26.350+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:54:26.432+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:54:26.430+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:54:26.432+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:54:26.450+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.110 seconds
[2023-07-23T09:54:56.480+0000] {processor.py:157} INFO - Started process (PID=540) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:54:56.480+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:54:56.481+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:54:56.481+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:54:56.546+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:54:56.544+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:54:56.546+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:54:56.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.085 seconds
[2023-07-23T09:55:26.679+0000] {processor.py:157} INFO - Started process (PID=548) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:55:26.681+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:55:26.681+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:55:26.681+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:55:26.759+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:55:26.757+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:55:26.760+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:55:26.776+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.100 seconds
[2023-07-23T09:56:23.071+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:56:23.071+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:56:23.072+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:56:23.072+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:56:23.258+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:56:23.257+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:56:23.259+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:56:23.283+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.215 seconds
[2023-07-23T09:56:53.396+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:56:53.398+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:56:53.400+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:56:53.399+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:56:53.593+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:56:53.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Scrape import Scrape
ModuleNotFoundError: No module named 'Scrape'
[2023-07-23T09:56:53.594+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:56:53.612+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.219 seconds
[2023-07-23T09:57:23.743+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:57:23.747+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:57:23.749+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:57:23.748+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:57:24.119+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:57:24.118+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T09:57:24.119+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:57:24.144+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.413 seconds
[2023-07-23T09:57:54.339+0000] {processor.py:157} INFO - Started process (PID=54) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:57:54.339+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:57:54.340+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:57:54.340+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:57:54.404+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:57:54.402+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T09:57:54.404+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:57:54.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.084 seconds
[2023-07-23T09:58:24.452+0000] {processor.py:157} INFO - Started process (PID=62) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:58:24.453+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:58:24.454+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:58:24.453+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:58:24.517+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:58:24.516+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T09:58:24.518+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:58:24.534+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.085 seconds
[2023-07-23T09:58:54.628+0000] {processor.py:157} INFO - Started process (PID=70) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:58:54.637+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:58:54.637+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:58:54.637+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:58:54.698+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:58:54.696+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T09:58:54.698+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:58:54.714+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.089 seconds
[2023-07-23T09:59:24.751+0000] {processor.py:157} INFO - Started process (PID=78) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:59:24.751+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:59:24.752+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:59:24.752+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:59:24.813+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:59:24.812+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T09:59:24.814+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:59:24.830+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.081 seconds
[2023-07-23T09:59:54.922+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/etl.py
[2023-07-23T09:59:54.924+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T09:59:54.924+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:59:54.924+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T09:59:54.985+0000] {logging_mixin.py:150} INFO - [2023-07-23T09:59:54.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T09:59:54.985+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T09:59:55.001+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.081 seconds
[2023-07-23T10:00:25.049+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:00:25.049+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:00:25.050+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:00:25.050+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:00:25.118+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:00:25.117+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:00:25.118+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:00:25.133+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.088 seconds
[2023-07-23T10:00:55.218+0000] {processor.py:157} INFO - Started process (PID=101) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:00:55.221+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:00:55.221+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:00:55.221+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:00:55.281+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:00:55.280+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:00:55.281+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:00:55.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.080 seconds
[2023-07-23T10:01:25.359+0000] {processor.py:157} INFO - Started process (PID=109) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:01:25.360+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:01:25.360+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:01:25.360+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:01:25.421+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:01:25.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:01:25.422+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:01:25.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.079 seconds
[2023-07-23T10:01:55.498+0000] {processor.py:157} INFO - Started process (PID=117) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:01:55.499+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:01:55.499+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:01:55.499+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:01:55.559+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:01:55.558+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:01:55.560+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:01:55.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.080 seconds
[2023-07-23T10:02:25.650+0000] {processor.py:157} INFO - Started process (PID=125) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:02:25.651+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:02:25.651+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:02:25.651+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:02:25.713+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:02:25.712+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:02:25.714+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:02:25.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.083 seconds
[2023-07-23T10:02:55.779+0000] {processor.py:157} INFO - Started process (PID=133) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:02:55.789+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:02:55.789+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:02:55.789+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:02:55.851+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:02:55.850+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:02:55.851+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:02:55.882+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.106 seconds
[2023-07-23T10:03:25.951+0000] {processor.py:157} INFO - Started process (PID=141) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:03:25.952+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:03:25.952+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:03:25.952+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:03:26.013+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:03:26.012+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:03:26.014+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:03:26.030+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.081 seconds
[2023-07-23T10:03:56.090+0000] {processor.py:157} INFO - Started process (PID=149) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:03:56.098+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:03:56.099+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:03:56.099+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:03:56.166+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:03:56.165+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:03:56.166+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:03:56.186+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.098 seconds
[2023-07-23T10:04:26.240+0000] {processor.py:157} INFO - Started process (PID=157) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:04:26.240+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:04:26.241+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:04:26.241+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:04:26.302+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:04:26.301+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:04:26.302+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:04:26.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.081 seconds
[2023-07-23T10:04:56.396+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:04:56.406+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:04:56.406+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:04:56.406+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:04:56.468+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:04:56.467+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:04:56.469+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:04:56.485+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.092 seconds
[2023-07-23T10:05:26.538+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:05:26.538+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:05:26.539+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:05:26.539+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:05:26.615+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:05:26.613+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 5, in <module>
    from Transform import Transform
ModuleNotFoundError: No module named 'Transform'
[2023-07-23T10:05:26.615+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:05:26.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.099 seconds
[2023-07-23T10:05:56.702+0000] {processor.py:157} INFO - Started process (PID=180) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:05:56.702+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:05:56.703+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:05:56.703+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:05:56.766+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:05:56.765+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:05:56.766+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:05:56.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.084 seconds
[2023-07-23T10:06:26.884+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:06:26.885+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:06:26.886+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:06:26.885+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:06:26.954+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:06:26.952+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:06:26.955+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:06:26.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.088 seconds
[2023-07-23T10:06:57.011+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:06:57.019+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:06:57.020+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:06:57.020+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:06:57.092+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:06:57.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:06:57.093+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:06:57.110+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.102 seconds
[2023-07-23T10:07:27.199+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:07:27.200+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:07:27.201+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:07:27.201+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:07:27.270+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:07:27.269+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:07:27.271+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:07:27.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.093 seconds
[2023-07-23T10:07:57.328+0000] {processor.py:157} INFO - Started process (PID=212) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:07:57.330+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:07:57.330+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:07:57.330+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:07:57.396+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:07:57.395+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:07:57.396+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:07:57.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.087 seconds
[2023-07-23T10:08:27.512+0000] {processor.py:157} INFO - Started process (PID=220) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:08:27.512+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:08:27.513+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:08:27.513+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:08:27.574+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:08:27.572+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:08:27.574+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:08:27.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.080 seconds
[2023-07-23T10:08:57.643+0000] {processor.py:157} INFO - Started process (PID=228) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:08:57.645+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:08:57.645+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:08:57.645+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:08:57.709+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:08:57.708+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:08:57.709+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:08:57.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.085 seconds
[2023-07-23T10:09:27.802+0000] {processor.py:157} INFO - Started process (PID=236) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:09:27.803+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:09:27.803+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:09:27.803+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:09:27.869+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:09:27.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:09:27.869+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:09:27.886+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.086 seconds
[2023-07-23T10:09:57.938+0000] {processor.py:157} INFO - Started process (PID=244) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:09:57.939+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:09:57.939+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:09:57.939+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:09:58.009+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:09:58.008+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:09:58.010+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:09:58.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.094 seconds
[2023-07-23T10:10:28.109+0000] {processor.py:157} INFO - Started process (PID=252) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:10:28.109+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:10:28.110+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:10:28.110+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:10:28.206+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:10:28.204+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:10:28.206+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:10:28.226+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.120 seconds
[2023-07-23T10:10:58.247+0000] {processor.py:157} INFO - Started process (PID=260) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:10:58.256+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:10:58.258+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:10:58.257+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:10:58.351+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:10:58.349+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:10:58.351+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:10:58.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.130 seconds
[2023-07-23T10:11:28.472+0000] {processor.py:157} INFO - Started process (PID=268) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:11:28.473+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:11:28.473+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:11:28.473+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:11:28.534+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:11:28.533+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:11:28.535+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:11:28.551+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.081 seconds
[2023-07-23T10:11:58.595+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:11:58.597+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:11:58.597+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:11:58.597+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:11:58.665+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:11:58.662+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:11:58.665+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:11:58.685+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.092 seconds
[2023-07-23T10:13:20.127+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:13:20.128+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:13:20.129+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:13:20.129+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:13:20.310+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:13:20.309+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:13:20.311+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:13:20.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.201 seconds
[2023-07-23T10:13:50.432+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:13:50.434+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:13:50.435+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:13:50.434+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:13:50.586+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:13:50.585+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:13:50.586+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:13:50.599+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.169 seconds
[2023-07-23T10:14:20.706+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:14:20.706+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:14:20.707+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:14:20.707+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:14:20.857+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:14:20.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 6, in <module>
    from src.Load import Load
  File "/opt/airflow/dags/src/Load.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-07-23T10:14:20.858+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:14:20.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.168 seconds
[2023-07-23T10:59:00.824+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:59:00.825+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:59:00.826+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:00.826+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:59:01.026+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:59:01.177+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:01.177+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:toronto_real_estate_etl
[2023-07-23T10:59:01.186+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:01.186+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:toronto_real_estate_etl
[2023-07-23T10:59:01.197+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:01.197+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:toronto_real_estate_etl
[2023-07-23T10:59:01.215+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:01.214+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T10:59:01.227+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:01.227+0000] {dag.py:2763} INFO - Creating ORM DAG for toronto_real_estate_etl
[2023-07-23T10:59:01.237+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:01.237+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T10:59:01.259+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.438 seconds
[2023-07-23T10:59:31.379+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/etl.py
[2023-07-23T10:59:31.379+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T10:59:31.381+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:31.380+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T10:59:31.536+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T10:59:31.555+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:31.555+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T10:59:31.570+0000] {logging_mixin.py:150} INFO - [2023-07-23T10:59:31.570+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T10:59:31.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.208 seconds
[2023-07-23T11:00:01.689+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:00:01.691+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:00:01.692+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:00:01.692+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:00:01.829+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:00:01.846+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:00:01.846+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:00:01.860+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:00:01.860+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:00:01.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.188 seconds
[2023-07-23T11:00:32.087+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:00:32.089+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:00:32.090+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:00:32.090+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:00:32.160+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:00:32.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
ImportError: cannot import name 'main' from 'src.main' (/opt/airflow/dags/src/main.py)
[2023-07-23T11:00:32.160+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:00:32.177+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.093 seconds
[2023-07-23T11:01:02.211+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:01:02.212+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:01:02.213+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:01:02.213+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:01:02.220+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:01:02.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 65
    def transform()
                      ^
SyntaxError: invalid syntax
[2023-07-23T11:01:02.221+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:01:02.259+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.053 seconds
[2023-07-23T11:01:31.328+0000] {processor.py:157} INFO - Started process (PID=71) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:01:31.329+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:01:31.329+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:01:31.329+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:01:31.333+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:01:31.332+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 65
    def transform()
                      ^
SyntaxError: invalid syntax
[2023-07-23T11:01:31.333+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:01:31.347+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.023 seconds
[2023-07-23T11:01:36.379+0000] {processor.py:157} INFO - Started process (PID=72) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:01:36.380+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:01:36.380+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:01:36.380+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:01:36.384+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:01:36.383+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
  File "/opt/airflow/dags/src/main.py", line 65
    def transform()
                      ^
SyntaxError: invalid syntax
[2023-07-23T11:01:36.384+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:01:36.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.023 seconds
[2023-07-23T11:02:06.527+0000] {processor.py:157} INFO - Started process (PID=80) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:02:06.536+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:02:06.536+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:06.536+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:02:06.600+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:06.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
ImportError: cannot import name 'main' from 'src.main' (/opt/airflow/dags/src/main.py)
[2023-07-23T11:02:06.601+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:02:06.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.092 seconds
[2023-07-23T11:02:26.618+0000] {processor.py:157} INFO - Started process (PID=81) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:02:26.619+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:02:26.619+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:26.619+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:02:26.691+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:26.690+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
ImportError: cannot import name 'main' from 'src.main' (/opt/airflow/dags/src/main.py)
[2023-07-23T11:02:26.692+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:02:26.709+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.093 seconds
[2023-07-23T11:02:29.709+0000] {processor.py:157} INFO - Started process (PID=89) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:02:29.709+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:02:29.710+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:29.710+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:02:29.772+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:29.771+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
ImportError: cannot import name 'main' from 'src.main' (/opt/airflow/dags/src/main.py)
[2023-07-23T11:02:29.773+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:02:29.787+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.081 seconds
[2023-07-23T11:02:41.781+0000] {processor.py:157} INFO - Started process (PID=90) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:02:41.791+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:02:41.792+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:41.792+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:02:41.856+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:41.855+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
ImportError: cannot import name 'main' from 'src.main' (/opt/airflow/dags/src/main.py)
[2023-07-23T11:02:41.856+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:02:41.874+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.095 seconds
[2023-07-23T11:02:54.889+0000] {processor.py:157} INFO - Started process (PID=91) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:02:54.889+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:02:54.890+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:54.890+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:02:54.953+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:02:54.952+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
ImportError: cannot import name 'main' from 'src.main' (/opt/airflow/dags/src/main.py)
[2023-07-23T11:02:54.954+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:02:54.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.084 seconds
[2023-07-23T11:03:00.946+0000] {processor.py:157} INFO - Started process (PID=99) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:03:00.947+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:03:00.948+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:03:00.948+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:03:01.013+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:03:01.011+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 7, in <module>
    from src.main import main
ImportError: cannot import name 'main' from 'src.main' (/opt/airflow/dags/src/main.py)
[2023-07-23T11:03:01.013+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:03:01.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.084 seconds
[2023-07-23T11:03:27.100+0000] {processor.py:157} INFO - Started process (PID=100) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:03:27.109+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:03:27.110+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:03:27.110+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:03:27.191+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:03:27.188+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 34, in <module>
    python_callable=extract,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'scrape listings' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-07-23T11:03:27.192+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:03:27.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.109 seconds
[2023-07-23T11:03:57.223+0000] {processor.py:157} INFO - Started process (PID=108) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:03:57.224+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:03:57.224+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:03:57.224+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:03:57.294+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:03:57.293+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 34, in <module>
    python_callable=extract,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'scrape listings' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-07-23T11:03:57.294+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:03:57.324+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.103 seconds
[2023-07-23T11:04:17.408+0000] {processor.py:157} INFO - Started process (PID=116) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:04:17.418+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:04:17.418+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:04:17.418+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:04:17.487+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:04:17.486+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 34, in <module>
    python_callable=extract,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'scrape listings' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-07-23T11:04:17.487+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:04:17.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.097 seconds
[2023-07-23T11:04:26.454+0000] {processor.py:157} INFO - Started process (PID=117) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:04:26.455+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:04:26.456+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:04:26.455+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:04:26.537+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:04:26.536+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 34, in <module>
    python_callable=extract,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'scrape listings' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-07-23T11:04:26.538+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:04:26.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.104 seconds
[2023-07-23T11:04:56.671+0000] {processor.py:157} INFO - Started process (PID=125) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:04:56.673+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:04:56.673+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:04:56.673+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:04:56.737+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:04:56.736+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 34, in <module>
    python_callable=extract,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'scrape listings' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-07-23T11:04:56.737+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:04:56.752+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.084 seconds
[2023-07-23T11:05:26.806+0000] {processor.py:157} INFO - Started process (PID=133) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:05:26.806+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:05:26.808+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:05:26.807+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:05:26.877+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:05:26.876+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 34, in <module>
    python_callable=extract,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'scrape listings' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-07-23T11:05:26.877+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:05:26.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.091 seconds
[2023-07-23T11:05:43.926+0000] {processor.py:157} INFO - Started process (PID=141) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:05:43.928+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:05:43.929+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:05:43.929+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:05:44.010+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:05:44.116+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:05:44.116+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:05:44.137+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:05:44.137+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:05:44.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.241 seconds
[2023-07-23T11:06:14.277+0000] {processor.py:157} INFO - Started process (PID=148) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:06:14.278+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:06:14.279+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:06:14.278+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:06:14.364+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:06:14.396+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:06:14.396+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:06:14.414+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:06:14.414+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:06:14.429+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.155 seconds
[2023-07-23T11:06:44.537+0000] {processor.py:157} INFO - Started process (PID=156) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:06:44.539+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:06:44.539+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:06:44.539+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:06:44.607+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:06:44.631+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:06:44.630+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:06:44.649+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:06:44.649+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:06:44.663+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.129 seconds
[2023-07-23T11:07:14.767+0000] {processor.py:157} INFO - Started process (PID=164) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:07:14.767+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:07:14.768+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:07:14.767+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:07:14.843+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:07:14.869+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:07:14.868+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:07:14.887+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:07:14.887+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:07:14.900+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.136 seconds
[2023-07-23T11:07:45.011+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:07:45.013+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:07:45.014+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:07:45.014+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:07:45.082+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:07:45.106+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:07:45.105+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:07:45.124+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:07:45.124+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:07:45.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.133 seconds
[2023-07-23T11:08:15.256+0000] {processor.py:157} INFO - Started process (PID=180) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:08:15.257+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:08:15.258+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:08:15.258+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:08:15.325+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:08:15.349+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:08:15.348+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:08:15.365+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:08:15.365+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:08:15.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.127 seconds
[2023-07-23T11:08:45.483+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:08:45.491+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:08:45.492+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:08:45.492+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:08:45.558+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:08:45.581+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:08:45.581+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:08:45.599+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:08:45.599+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:08:45.615+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.135 seconds
[2023-07-23T11:09:15.718+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:09:15.719+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:09:15.719+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:09:15.719+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:09:15.788+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:09:15.811+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:09:15.810+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:09:15.827+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:09:15.827+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:09:15.843+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.127 seconds
[2023-07-23T11:09:45.945+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:09:45.954+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:09:45.955+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:09:45.955+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:09:46.024+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:09:46.048+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:09:46.048+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:09:46.066+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:09:46.066+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:09:46.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.140 seconds
[2023-07-23T11:10:16.195+0000] {processor.py:157} INFO - Started process (PID=212) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:10:16.196+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:10:16.196+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:10:16.196+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:10:16.275+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:10:16.311+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:10:16.310+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:10:16.338+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:10:16.338+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:10:16.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.162 seconds
[2023-07-23T11:10:46.463+0000] {processor.py:157} INFO - Started process (PID=220) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:10:46.466+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:10:46.467+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:10:46.466+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:10:46.536+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:10:46.560+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:10:46.559+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:10:46.578+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:10:46.578+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:10:46.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.134 seconds
[2023-07-23T11:11:16.693+0000] {processor.py:157} INFO - Started process (PID=228) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:11:16.694+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:11:16.695+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:11:16.694+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:11:16.763+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:11:16.784+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:11:16.784+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:11:16.801+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:11:16.801+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:11:16.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.124 seconds
[2023-07-23T11:11:46.913+0000] {processor.py:157} INFO - Started process (PID=236) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:11:46.915+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:11:46.915+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:11:46.915+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:11:46.979+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:11:47.004+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:11:47.004+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:11:47.020+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:11:47.020+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:11:47.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.125 seconds
[2023-07-23T11:12:17.130+0000] {processor.py:157} INFO - Started process (PID=244) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:12:17.131+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:12:17.131+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:12:17.131+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:12:17.198+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:12:17.221+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:12:17.220+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:12:17.239+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:12:17.239+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:12:17.256+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.129 seconds
[2023-07-23T11:12:47.381+0000] {processor.py:157} INFO - Started process (PID=252) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:12:47.384+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:12:47.384+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:12:47.384+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:12:47.452+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:12:47.474+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:12:47.474+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:12:47.491+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:12:47.491+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:12:47.506+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.128 seconds
[2023-07-23T11:13:17.606+0000] {processor.py:157} INFO - Started process (PID=260) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:13:17.606+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:13:17.607+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:13:17.606+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:13:17.671+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:13:17.695+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:13:17.694+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:13:17.712+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:13:17.712+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:13:17.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.123 seconds
[2023-07-23T11:13:47.825+0000] {processor.py:157} INFO - Started process (PID=268) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:13:47.834+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:13:47.835+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:13:47.835+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:13:47.899+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:13:47.922+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:13:47.921+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:13:47.938+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:13:47.938+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:13:47.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.131 seconds
[2023-07-23T11:14:18.047+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:14:18.048+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:14:18.048+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:14:18.048+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:14:18.113+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:14:18.138+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:14:18.138+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:14:18.156+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:14:18.156+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:14:18.169+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.124 seconds
[2023-07-23T11:14:48.271+0000] {processor.py:157} INFO - Started process (PID=284) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:14:48.280+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:14:48.281+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:14:48.281+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:14:48.344+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:14:48.365+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:14:48.365+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:14:48.382+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:14:48.381+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:14:48.395+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.127 seconds
[2023-07-23T11:15:18.494+0000] {processor.py:157} INFO - Started process (PID=292) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:15:18.494+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:15:18.495+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:15:18.495+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:15:18.556+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:15:18.578+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:15:18.577+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:15:18.594+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:15:18.594+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:15:18.610+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.119 seconds
[2023-07-23T11:15:48.717+0000] {processor.py:157} INFO - Started process (PID=300) to work on /opt/airflow/dags/etl.py
[2023-07-23T11:15:48.726+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2023-07-23T11:15:48.727+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:15:48.727+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2023-07-23T11:15:48.789+0000] {processor.py:836} INFO - DAG(s) dict_keys(['toronto_real_estate_etl']) retrieved from /opt/airflow/dags/etl.py
[2023-07-23T11:15:48.812+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:15:48.812+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-07-23T11:15:48.829+0000] {logging_mixin.py:150} INFO - [2023-07-23T11:15:48.829+0000] {dag.py:3508} INFO - Setting next_dagrun for toronto_real_estate_etl to 2022-05-26T00:00:00+00:00, run_after=2022-05-27T00:00:00+00:00
[2023-07-23T11:15:48.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl.py took 0.130 seconds
